### ISSUE TITLE
Automate the execution of commands with Cake

### ISSUE THREAD

**Issue by dcampbell24** [carlodicelico/reify#1]
[Cake][cake] is a simple build tool that saves time by tracking command dependencies, enforcing static guarantees, and stealing work.

[cake]: https://github.com/ticki/cake

Here is an example of using a [cakefile][go-cakefile] to build Go code. The Redox kernel has a [cakefile][kernel-cakefile] too.

[go-cakefile]: https://github.com/dcampbell24/cubes/blob/master/cakefile.rs
[kernel-cakefile]: https://github.com/redox-os/kernel/blob/master/cakefile.rs

For this ticket, implement something that will reduce the size of the [Quick Start Guide][quick-start].

 [quick-start]: https://github.com/carlodicelico/reify/blob/master/README.md#user-content-quick-start-guide

**Comment by carlodicelico** [comment]
Cake looks pretty neat, thanks for sharing! Unfortunately, it's neither widely adopted nor idiomatic to node or React development - two requirements for any library included here. I'm also not sure that there is a problem to solve here with cake. The way this project is set up is pretty typical for node projects and is actually quite minimal already.
